version: '3.8'
name: EMS

services:
  mongo:
    image: mongo:6
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - EMS

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - EMS

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - EMS
    ports:
      - "8080:8080"
    depends_on:
      - mongo
      - redis
    command: npm run dev

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - EMS
    command: npm run dev
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  mongo_data:

networks:
  EMS:
    driver: bridge
